import bgMain from "./register.png"
import logo from './logo.png'
import frame8 from './Frame.png'
import setting from './Vector1.png';
import notif from './Vector2.svg'
import notif2 from './Vector3.svg';
import grid from './grid.svg';
import headset from './headset.svg';
import chimney from './chimney.svg';
import inbox from './inbox.svg';
import user from './user.svg';
import exit from './exit.svg';
import transfer from './transfer.svg'
import frame from './Frame-orange.svg'
import checkCircle from './circle-check.svg';
import frame2 from './Frame2.svg'
import frame3 from './Frame3.svg'
import frame4 from './Frame4.svg'
import frame5 from './Frame5.svg'
import plusCircle from './Vector4.svg'
import gridActive from './grid-active.svg';
import chimneyActive from './chimney-active.svg' 
import inboxActive from './inbox-active.svg'
import userActive from './user-active.svg'
import headsetActive from './headset-active.svg'
import map from './map.png'
import house from './house-flag.svg'
import circle from './file-circle.svg'
import certificate from './file-certificate.svg'
import building from './house-building.svg'
import bill from './bill.svg'
import buildingCircle from './building-circle.svg'
import houseMedical from './house-medical.svg'
import memo from './memo.svg'
import road from './road.svg'
import houseCheck from './house-check.svg'
import exportfile from './export.svg'
import signature from './signature.svg'
import line from './Line.svg'
import line2 from './line2.svg'
import checkmark from './checkmark.svg'

export{checkmark,line2,line,houseCheck,exportfile,signature,buildingCircle,houseMedical,memo,road,bill,building,house,circle,certificate,map,headsetActive,userActive,inboxActive,chimneyActive,gridActive,bgMain,logo , frame8 , setting , notif , notif2 , grid ,chimney,exit,headset,inbox,transfer,user ,frame ,checkCircle , frame2 , frame3 , frame4 , frame5 , plusCircle}